"""
Quick test to see if agents work
"""
import sys
import os

# Add current directory to path
sys.path.insert(0, os.getcwd())

print("🧪 Testing agent import...")

try:
    from agents.base_agent import BaseShaktiAgent
    print(f"✅ Base agent imported successfully!")
    
    # Test creating a simple agent
    agent = BaseShaktiAgent(
        name="TestAgent",
        description="Test agent",
        personality="Test personality", 
        expertise=["testing"],
        tone="friendly"
    )
    
    print(f"✅ Agent created: {agent.name}")
    
    # Test content generation
    print("🔄 Testing content generation...")
    result = agent.generate_content("social_media_post", "test prompt")
    print(f"✅ Content generated! Title: {result['title']}")
    print(f"✅ Content length: {len(result['content'])} characters")
    print(f"✅ Generated by: {result['metadata']['generatedBy']}")
    
    if "Fallback" in result['metadata']['generatedBy']:
        print("❌ WARNING: Using fallback, not real AI!")
    else:
        print("✅ SUCCESS: Real AI content generated!")

except Exception as e:
    print(f"❌ Error: {e}")
    import traceback
    traceback.print_exc()
